Fine tune on english data
pwr-ai/JuDDGES pull request #30
Opened 2024-08-29 14:49 UTC by binkjakub

2024-10-01 11:09 UTC, asawczyn requested changes

2024-10-01 11:09 UTC, asawczyn commented on nbs/Data/01_Dataset_Description.ipynb
> +   "execution_count": 1,
do we want it executed?

2024-10-01 11:09 UTC, asawczyn commented on nbs/Dataset Cards/01_Dataset_Description_Raw.ipynb
> +   "execution_count": 16,
do we want it executed?

2024-10-01 13:15 UTC, binkjakub commented on nbs/Data/01_Dataset_Description.ipynb
> +   "execution_count": 1,
description - yes

2024-10-01 13:15 UTC, binkjakub commented on nbs/Dataset Cards/01_Dataset_Description_Raw.ipynb
> +   "execution_count": 16,
cleaned it

2024-10-02 08:52 UTC, asawczyn approved these changes

2024-10-02 08:53 UTC, merged